version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 9000  # Expose le port PHP-FPM pour Nginx
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    ports:
      - "${APP_PORT}:80"  # Expose le port Nginx à votre machine hôte
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Configuration Nginx
      - .:/var/www/html  # Synchro des fichiers de l'application avec Nginx
    depends_on:
      - app

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
